### ISSUE TITLE
Snippets / akeeba backup core conflict

### ISSUE THREAD

**Issue by danielbierstedt** [artstorm/post-snippets#37]
I'm not able to start a backup using akeeba core when Post Snippet is active. Screenshot from the Chrome console is attached.

Wordpress: 4.0.1
Post Snippet: 2.3.4
Akeeba: 1.2.0.rc6
![akeeba_error](https://cloud.githubusercontent.com/assets/9999431/5437097/b7186d54-846d-11e4-910b-84182f777163.png)

**Comment by artstorm** [comment]
I've finally got around catching up on some old issues. I was not able to reproduce this with the latest Akeeba plugin/Post Snippets/WordPress, so I assume that whatever was causing the issue has been resolved by itself over the versions since this issue.

If not, feel free to let me know and I'll reopen it.
